version: '3.9'

services:
  java_app:
    container_name: java_app
    #Nombre que le queremos dar a nuestra imagen
    image: java-app:1.0.0      
    build: .
    ports:
      - 3000:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/users
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1234
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:8.2.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=users